#!/bin/sh
set -e

case "$1" in
    remove|deconfigure)
        systemctl stop terraform-backend.service >/dev/null 2>&1 || true
        systemctl disable terraform-backend.service >/dev/null 2>&1 || true
        ;;
esac
